### ISSUE TITLE
As a chat user, I wish to have access to a setting page, so that I can configure my application to my preferences

### ISSUE THREAD

**Issue by Enderknight2016** [p2pchat/p2pChat#16]
Acceptance criteria:
- buttons for changing the application theme are present, even if they don't change the theme.
- A way to view the user's full device information is given.
- a way to access a separate fragment, the nickname list, is given.
- the settings exist in a fragment, not an activity
- add a setting for message history length to resolve issue #10 with a default of never forgetting a message (implementation can wait until #14 is finished)

**Comment by Madministrator** [comment]
Acceptance criteria:
- buttons for changing the application theme are present, even if they don't change the theme.
- A way to view the user's full device information is given.
- a way to access a separate fragment, the nickname list, is given.
- the settings exist in a fragment, not an activity
