### ISSUE TITLE
As a programmer, I need to research if there is a standard format for android chat applications, and how our app can use it to build the actual GUI faster.

### ISSUE THREAD

**Issue by Madministrator** [p2pchat/p2pChat#17]

**Comment by Madministrator** [comment]
acceptance criteria:
- a wiki page describing a android standard chat system, if any, including links to the original documentation
- the documentation shall include any relevant data models used by chat applications, and list pros and cons for each type of data model
- the documentation shall include user experience design flaws encountered in other popular chat applications, so that we can avoid potential pitfalls

**Comment by Enderknight2016** [comment]
https://github.com/p2pchat/p2pChat/wiki/Chat-Frameworks-and-Options

**Comment by Madministrator** [comment]
Missing acceptance criteria 3: you can fix this by addressing WHY certain approaches are "hardmode" and a guide to how to create the chat view would be great. There is nothing about what kind of model we need and how we push data to the view. As it is we cannot hand the chat application off to another developer.

**Comment by Madministrator** [comment]
I've approved this issue as reviewer
