### ISSUE TITLE
As a programmer, I need to research how we can integrate with other Android applications, such as Android photos, to allow us to expand functionality.

### ISSUE THREAD

**Issue by Madministrator** [p2pchat/p2pChat#18]

**Comment by Madministrator** [comment]
start by looking up the difference between explicit and implicit intents and how to create them

**Comment by Enderknight2016** [comment]
https://github.com/p2pchat/p2pChat/wiki/App-Integration

**Comment by Enderknight2016** [comment]
acceptance criteria:

* have a list of potential applications we can integrate with, elaborating on how we would integrate with each
* a page is in the wiki describing how we can integrate our app with the android OS, including links to the documentation where the research was gathered.
