### ISSUE TITLE
As an imperfect programmer we need a java linter configured and added to the project to enforce style guidlines so we make fewer silly style mistakes

### ISSUE THREAD

**Issue by Austin-Scott** [p2pchat/p2pChat#21]

**Comment by Madministrator** [comment]
acceptance criteria:
- a linter configuration file is added to the android studio project, and can be added to each member's project
- the linter shall enforce inline code documentation
- the linter shall enforce all code styles on our wiki
- the assignee must demonstrate that the linter is able to catch mistakes by creating a temporary bad file to show that the linter works. (This bad file must be deleted before merging with master)

**Comment by Madministrator** [comment]
https://developer.android.com/studio/write/lint
http://tools.android.com/tips/lint

**Comment by zolondekn9689** [comment]
Setting up the plugin needed to modify lint. 
Link: https://github.com/p2pchat/p2pChat/wiki/Setup-Plugin-Configuration
