### ISSUE TITLE
As a programmer on this team, I need documentation on the wiki about the workflow of each Sprint so that we have a plan to follow

### ISSUE THREAD

**Issue by Austin-Scott** [p2pchat/p2pChat#22]
acceptance criteria:
- a wiki page must be created containing:
    - instructions on what needs to be accomplished for each column of the sprint board
    - rules for the review process
    - screenshots of the github GUI showing us how to do the different tasks

**Comment by Madministrator** [comment]
acceptance criteria:
- a wiki page must be created containing:
    - instructions on what needs to be accomplished for each column of the sprint board
    - rules for the review process
    - screenshots of the github GUI showing us how to do the different tasks

**Comment by Madministrator** [comment]
closed because this would only have been helpful in sprint 1, which we have passed
