### ISSUE TITLE
As a QA tester, I want to research a testing framework so that the entire team can work together to test the app

### ISSUE THREAD

**Issue by Austin-Scott** [p2pchat/p2pChat#3]

**Comment by Madministrator** [comment]
acceptance criteria:
- documentation must include how to write a test, including style standards
- links to the original documentation must be included in the wiki
- any tools, extensions, or dependencies needed for the testing framework shall be installed into Android Studio, or a guide detailing how to install them must be written.
- a demonstration test must be written proving that the testing framework is working

**Comment by Austin-Scott** [comment]
* Continuous integration must be added and proved to be working

**Comment by Austin-Scott** [comment]
Wiki added here: https://github.com/p2pchat/p2pChat/wiki/Unit-Testing
