### ISSUE TITLE
As a programmer, I need a set of style standards to keep code neat and well documented

### ISSUE THREAD

**Issue by Austin-Scott** [p2pchat/p2pChat#6]
These standards shall be posted on the repository

**Comment by Madministrator** [comment]
- There is a page on the repository wiki with a style guide
- All style criteria are agreed upon by members of the project

**Comment by zolondekn9689** [comment]
Link to wiki: https://github.com/p2pchat/p2pChat/wiki/Setup-Android-Coding-Style

**Comment by Madministrator** [comment]
can we get the download location of the style file put into the github repository? Maybe there is a way to add it to the Wiki repository? I don't want it hosted separately from the github repository.
