### ISSUE TITLE
As a QA tester, I need to mock the WifiDirect class so I can test connecting to other devices from an integration test so we can be assured that it works

### ISSUE THREAD

**Issue by Austin-Scott** [p2pchat/p2pChat#76]
Acceptance Criteria:

  * WifiDirect class will have a mock version created
  * The fragments interacting with the WifiDirect class will be tested inside of UI integration tests to verify that the process of connecting to peers works as expected

**Comment by zolondekn9689** [comment]
Acceptance Criteria: 
- Be able to verify WifiDirect class can send data two ways.
